# نسخه اصلاح شده برای استفاده از bind mount برای مدیا
services:
  db:
    image: mysql:8.0
    container_name: quiz-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # فقط این والیوم برای ذخیره دائمی داده‌های دیتابیس استفاده می‌شود
      - db_data:/var/lib/mysql
    networks:
      - quiz_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: .
    container_name: quiz-web
    restart: always
    command: ["gunicorn", "-c", "./gunicorn.conf.py", "wsgi:application"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      # مپ کردن پوشه مدیا از هاست به کانتینر
      - ./static/media:/app/static/media  # مسیر هاست: ./static/media (نسبت به docker-compose.yml)
      # برای توسعه، می‌توانید کد را هم مپ کنید، اما برای پروداکشن بهتر است در ایمیج باشد
      # اگر می‌خواهید تغییرات کد پایتون هم بلافاصله در کانتینر دیده شود، این خط را از کامنت خارج کنید:
      # - .:/app
    env_file:
      - .env
    networks:
      - quiz_network

  bot:
    build: . # از همان Dockerfile برای ساخت ایمیج استفاده می‌کند
    container_name: quiz-bot-instance
    restart: always
    command: ["python", "run_bot.py"] # اسکریپت جدید برای اجرای ربات
    depends_on:
      db:
        condition: service_healthy
    volumes:
       # دسترسی به پوشه مدیا از هاست به این کانتینر نیز
      - ./static/media:/app/static/media # مسیر هاست: ./static/media
      # اگر ربات نیاز به خواندن مستقیم کدها از هاست دارد (برای توسعه)، این خط را از کامنت خارج کنید:
      # - .:/app
    env_file:
      - .env
    networks:
      - quiz_network

volumes:
  db_data: # فقط db_data به عنوان named volume باقی می‌ماند

networks:
  quiz_network:
    driver: bridge
